#!/bin/bash

#    (c) 2018-2021 kaalam.ai (The Authors of Jazz)
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

docker_pwd=$(pwd)

cd ../server || return 1

make jazz
cp jazz ../docker
make clean

cd "$docker_pwd" || return 1

cp ../server/config/jazz_config.ini .

docker build -t jazz_ref_stable .

docker login
